name: build docker image

on: push

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build testsuite image
        uses: docker/build-push-action@v2
        with:
          tags: italiangrid/argus-testsuite:gh
          context: docker/testsuite
          file: ./docker/testsuite/Dockerfile
          push: false

      - name: Push docker image
        run: docker push italiangrid/argus-testsuite:gh
