name: build docker image

on: 
  schedule:
    - cron: 0 1 * * *
  push:
  pull_request:

jobs:

  build-and-push-docker-testsuite:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta for testsuite
        id: meta_ts
        uses: docker/metadata-action@v3
        with:
          images: argus/argus-testsuite
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=tag

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: docker/testsuite
          file: ./docker/testsuite/Dockerfile
          push: true
          tags: ${{ steps.meta_ts.outputs.tags }}
          labels: ${{ steps.meta_ts.outputs.labels }}

  build-and-push-docker-argus:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta for argus
        id: meta_argus
        uses: docker/metadata-action@v3
        with:
          images: argus/argus-deployment-test-centos7
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=tag

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: docker/all-in-one-centos7
          file: ./docker/all-in-one-centos7/Dockerfile
          push: true
          tags: ${{ steps.meta_argus.outputs.tags }}
          labels: ${{ steps.meta_argus.outputs.labels }}